INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_LIMESUITE LimeSuite)

FIND_PATH(
    LIB_LIMESUITE_INCLUDE_DIRS
    NAMES lime/LimeSuite.h
    HINTS ${PC_LIMESUITE_INCLUDEDIR}
        ${CMAKE_INSTALL_PREFIX}/include/lime
    PATHS /usr/local/include/lime
          /usr/include/lime
)

FIND_LIBRARY(
    LIB_LIMESUITE_LIBRARIES
    NAMES LimeSuite
    HINTS ${PC_LIMESUITE_LIBDIR}
        ${CMAKE_INSTALL_PREFIX}/lib
        ${CMAKE_INSTALL_PREFIX}/lib64
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

message(" * INCLUDE=${LIB_LIMESUITE_INCLUDE_DIRS}")
message(" * LIBDIR=${LIB_LIMESUITE_LIBRARIES}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIB_LIMESUITE DEFAULT_MSG LIB_LIMESUITE_LIBRARIES LIB_LIMESUITE_INCLUDE_DIRS)
MARK_AS_ADVANCED(LIB_LIMESUITE_LIBRARIES LIB_LIMESUITE_INCLUDE_DIRS)

message(" * FOUND=${LIB_LIMESUITE_FOUND}")
